### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by FlyingBird95**

### CODE REVIEW

**Comment by mircealungu** [comment]
I normally prefer MIT. 
Is there a good reason for GPL-ing the code? 
@vandriko what do you think?

**Comment by vandriko** [comment]
Apache2? It's the one we usually use to avoid the GPL restrictions...

**Comment by mircealungu** [comment]
@FlyingBird95 @vandriko  @kloostert  - do you people agree with using MIT? Or you have a strong reason for going with a viral license?

**Comment by vandriko** [comment]
Fine with me...

**Comment by FlyingBird95** [comment]
MIT is also fine with me

**Comment by kloostert** [comment]
Yes, same here.

**Pull request closed without merging**
